---
title: "Fake Remote Sensing"
output: html_document
runtime: shiny
---

```{r, warning = FALSE, echo = FALSE}
library(tidyverse)
library(magick)
library(grid)
library(shiny)
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE, echo = FALSE}
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fileInput("file_upload", "Choose an image file", 
                accept = c("image/png", "image/jpeg", "image/jpg")),
      actionButton("plot", "Generate Plot")),
    mainPanel(
      fluidRow(
        column(6, h4("Original Image"), imageOutput("original_image")),
        column(6, h4("Clustered Image"), plotOutput("my_plot"))))))

server <- function(input, output) {
  addResourcePath("www", "www") # if needed to serve local resources
  session$setHeaders(
    "X-Frame-Options" = "SAMEORIGIN"  # This can also be "DENY" or ""
  )
  output$original_image <- renderImage({
    req(input$file_upload)
    list(
      src = input$file_upload$datapath,
      contentType = input$file_upload$type,
      width = "100%",
      alt = "Uploaded Image"
    )
  }, deleteFile = FALSE)

  plot_data <- eventReactive(input$plot, {
    req(input$file_upload)

    img <- image_read(input$file_upload$datapath)
    img <- image_resize(img, "100x100!")

    img_raster <- as.raster(img)
    df <- expand.grid(
      x = 1:ncol(img_raster),
      y = 1:nrow(img_raster)
    ) %>%
      mutate(color = as.vector(img_raster))

    df_rgb <- df %>%
      mutate(
        R = col2rgb(color)[1, ],
        G = col2rgb(color)[2, ],
        B = col2rgb(color)[3, ]
      )

    set.seed(42)
    k_clusters <- 8
    kmeans_result <- kmeans(df_rgb[, c("R", "G", "B")], centers = k_clusters)
    df_rgb$cluster <- factor(kmeans_result$cluster)

    ggplot(df_rgb, aes(x = x, y = -y, fill = cluster)) +
      geom_tile() +
      coord_fixed() +
      theme_void() +
      scale_fill_brewer(palette = "Dark2") +
      ggtitle(paste("Image Regions Clustered into", k_clusters, "Color Groups"))
  })

  output$my_plot <- renderPlot({
    req(plot_data())
    plot_data()
  })
}

shinyApp(ui = ui, server = server)
```



